#!/usr/bin/env bash
# Bash script that handles SIGTERM signal and displays "I am invincible!!!"

trapped_signal() {
	echo "I am invincible!!!"
}

trap trapped_signal 15

while true
do
	echo "To infinity and beyond"
	sleep 2
done
