#!/bin/bash
# This script displays "Best School" 10 times, but displays "Hi" on the 9th iteration

i=1
while [ $i -le 10 ]
#!/usr/bin/env bash
    if [ $i -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
